// Loading spinner
export const SHOW_LOADING_SPINNER = 'SHOW_LOADING_SPINNER';
export const HIDE_LOADING_SPINNER = 'HIDE_LOADING_SPINNER';

// News
export const SET_SEARCH_STRING = "SET_SEARCH_STRING";
export const SET_CATEGORY = "SET_CATEGORY";
export const TOGGLE_FAVOURITES_DRAWER = "TOGGLE_FAVOURITES_DRAWER";